In [1]:
import numpy as np
# shuffle
arr = np.array([2,3,1,0,9])
np.random.shuffle(arr)
print(arr)

[2 0 1 9 3]


In [2]:
# unique
arr1 = np.array([1,2,1,2,3,4,6,5,7,7,4,8,0,9,9])
print(np.unique(arr1))

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# resize
arr2 = np.array([1,2,3,4,5,6])
print(np.resize(arr2,(3,2)))

[[1 2]
 [3 4]
 [5 6]]


In [4]:
# ravel
arr3 = np.array([[1,2],[3,4]])
print(np.ravel(arr3))

[1 2 3 4]
