In [1]:
import numpy as np
# arange()
print(np.arange(5))
print(np.arange(1,6))
print(np.arange(1,8,2,dtype = float))

[0 1 2 3 4]
[1 2 3 4 5]
[1. 3. 5. 7.]


In [2]:
# zeros()
print(np.zeros(4, dtype = int))
print(np.zeros((2,2), dtype = int))

[0 0 0 0]
[[0 0]
 [0 0]]


In [3]:
# ones()
print(np.ones(3, dtype = int))
print(np.ones((3,3), dtype = int))

[1 1 1]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [4]:
# full()
print(np.full(5,20,dtype = int))
print(np.full((2,3),8))

[20 20 20 20 20]
[[8 8 8]
 [8 8 8]]


In [5]:
# reshape()
print(np.arange(6).reshape(2,3))
print(np.arange(6).reshape(-1))

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
