In [1]:
import numpy as np
# power()
arr = np.array([1,2,3,4])
print(np.power(arr,[2]))
print(np.power(arr,[2,3,4,5])) #differnt element diff power

[ 1  4  9 16]
[   1    8   81 1024]


In [2]:
# difference
arr1 = np.array([1,5,3,6])
print(np.diff(arr1))
print(np.diff((arr,arr1),axis = 0))

[ 4 -2  3]
[[0 3 0 2]]


In [3]:
# cross
arr2 = np.array([1,2])
arr3 = np.array([3,4])
print(np.cross(arr2,arr3))

-2


In [4]:
# sort
arr4 = np.array([2,1,6,3])
arr5 = np.array([0,9,4,7])
print(np.sort(arr4))
print(np.sort((arr4,arr5)))
print(np.sort((arr4,arr5),axis = 0))

[1 2 3 6]
[[1 2 3 6]
 [0 4 7 9]]
[[0 1 4 3]
 [2 9 6 7]]
