In [1]:
import numpy as np
# flatten
arr = np.array([[1,3,5,7],[2,4,6,8]])
print(arr.flatten())

[1 3 5 7 2 4 6 8]


In [2]:
# sum
print(arr.sum())
print(arr.sum(axis = 0))
print(arr.sum(axis = 1))

36
[ 3  7 11 15]
[16 20]


In [3]:
arr1 = np.array([[1,3,5,np.nan],[2,3,6,8]])
# nansum
print(arr1.sum())
print(np.nansum(arr1,axis = 0))
print(np.nansum(arr1,axis = 1))

nan
[ 3.  6. 11.  8.]
[ 9. 19.]


In [4]:
# cumsum
print(np.cumsum(arr, axis = 0))
print(np.cumsum(arr, axis = 1))

[[ 1  3  5  7]
 [ 3  7 11 15]]
[[ 1  4  9 16]
 [ 2  6 12 20]]


In [5]:
# cumprod
print(np.cumprod(arr,axis = 0))
print(np.cumprod(arr,axis = 1))

[[ 1  3  5  7]
 [ 2 12 30 56]]
[[  1   3  15 105]
 [  2   8  48 384]]
